### ISSUE TITLE
PROPOSAL: "snow streamlit run <file_name.py>"

### ISSUE THREAD

**Issue by sfc-gh-asaini** [Snowflake-Labs/snowflake-cli#24]
```sh
$ snow streamlit run streamlit_app.py
```

> Usage: snow streamlit run streamlit_app.py
> 
> Run the Streamlit app on Snowflake infrastructure and open the app in the browser. 

If the app does not exist, snowcli will create the object in Snowflake using the parameters stored in `app.toml`. To do so, 
add the following section to `app.toml`

```toml
snowsql_config_path = "config"
snowsql_connection_name = "testaccount_tmptest"

[dev]
database = "ST_DB"
schema = "ST_SCHEMA"
role = "SYSADMIN"
warehouse = "REGRESS"

[app]
name = "ABHI_CLI_TEST"
```

`$ snow streamlit run streamlit_app.py` works just like the library **streamlit** . 

The above command also monitors the local filesystem, so that if any file gets changed locally, then it detects the change and automatically triggers a `snow streamlit deploy NAME -o` under the hood.
